Repository smu06030/st8, pull requests merged in 2024-11, with the labels that each got.

#45 [#44] 회원가입 로그인 UI작업 및 버튼,인풋 컴포넌트 분리 Style/auth
  src/app/signup/[id]/page.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/signup/StepEmailForm.tsx
  src/components/auth/signup/StepNicknameForm.tsx
  src/components/auth/signup/StepPasswordForm.tsx
  src/components/common/Buttons/Button.tsx
  src/components/common/Buttons/LinkButton.tsx
  src/components/common/InputField.tsx
Labels: 리팩토링, 스타일

#46 [#44] add: common/icon/ 아이콘 19개 추가
  src/components/auth/LoginForm.tsx
  src/components/common/Icons/AlbumIcon.tsx
  src/components/common/Icons/BellIcon.tsx
  src/components/common/Icons/BookMarkIcon.tsx
  src/components/common/Icons/CheckIcon.tsx
  src/components/common/Icons/ComPass.tsx
  src/components/common/Icons/EtcIcon.tsx
  src/components/common/Icons/Eye2Icon.tsx
  src/components/common/Icons/EyeIcon.tsx
  src/components/common/Icons/HomeIcon.tsx
  src/components/common/Icons/LocationIcon.tsx
  src/components/common/Icons/LockIcon.tsx
  src/components/common/Icons/MailIcon.tsx
  src/components/common/Icons/MapIcon.tsx
  src/components/common/Icons/PlusIcon.tsx
  src/components/common/Icons/SearchIcon.tsx
  src/components/common/Icons/StampIcon.tsx
  src/components/common/Icons/StampIcon1.tsx
  src/components/common/Icons/UserIcon.tsx
  src/components/common/Icons/XIcon.tsx
  src/components/common/InputField.tsx
Labels: 스타일

#47 [#39] 메인 페이지 구현
  public/images/mainMap.png
  public/images/marker-pin-01.svg
  ro
  src/app/layout.tsx
  src/app/page.tsx
  src/app/stamp-map/loading.tsx
  src/app/stamp-map/page.tsx
  src/components/auth/LoginForm.tsx
  src/components/common/Icons/.gitkeep
  src/components/common/Icons/AlbumIcon.tsx
  src/components/common/Icons/BellIcon.tsx
  src/components/common/Icons/BookMarkIcon.tsx
  src/components/common/Icons/CheckIcon.tsx
  src/components/common/Icons/ComPass.tsx
  src/components/common/Icons/EtcIcon.tsx
  src/components/common/Icons/Eye2Icon.tsx
  src/components/common/Icons/EyeIcon.tsx
  src/components/common/Icons/HomeIcon.tsx
  src/components/common/Icons/Icon.tsx
  src/components/common/Icons/LocationIcon.tsx
  src/components/common/Icons/LockIcon.tsx
  src/components/common/Icons/MailIcon.tsx
  src/components/common/Icons/MainBackground.tsx
  src/components/common/Icons/MapIcon.tsx
  src/components/common/Icons/PlusIcon.tsx
  src/components/common/Icons/SearchIcon.tsx
  src/components/common/Icons/StampIcon.tsx
  src/components/common/Icons/StampIcon1.tsx
  src/components/common/Icons/UserIcon.tsx
  src/components/common/Icons/XIcon.tsx
  src/components/common/InputField.tsx
  src/components/common/Loading/Loading.tsx
  src/components/common/Modal/StampModal.tsx
  src/components/mainPage/MainPage.tsx
  src/components/stampMap/KakaoMap.tsx
  src/components/stampMap/KakaoMapMarker.tsx
  src/components/stampMap/KakaoMapOverlay.tsx
  src/components/stampMap/ReSetttingMapBounds.tsx
  src/components/stampMap/ScrollButtonSwiper.tsx
  src/constants/icons.ts
  src/hooks/useModal.tsx
  src/styles/swiper.css
  tailwind.config.ts
Labels: 기능 개발

#53 [#8] 스탬프 목록 비활성화 스탬프 리스트 추가
  public/images/testStamp.png
  public/images/강원특별자치도.png
  public/images/경기.png
  public/images/경남.png
  public/images/경북.png
  public/images/광주.png
  public/images/대전.png
  public/images/세종특별자치시.png
  public/images/울산.png
  public/images/전남.png
  public/images/제주특별자치시.png
  public/images/충남.png
  public/images/충북.png
  src/components/stamp/StampImg.ts
  src/components/stamp/StampItem.tsx
  src/components/stamp/StampList.tsx
Labels: 기능 개발

#54 [#50][#51]스탬프이미지 들어가는 부분 제외 css완료
  .gitignore
  src/app/globals.css
  src/app/stamp-all/[id]/page.tsx
  src/components/stamp/MyLocation.tsx
Labels: 스타일

#55 [#48] 모달창 뒷배경 스크롤 막기
  src/app/page.tsx
  src/app/stamp-map/loading.tsx
  src/app/stamp-map/page.tsx
  src/components/common/Icons/Icon.tsx
  src/components/common/Loading/Loading.tsx
  src/components/mainPage/MainFooter.tsx
  src/components/mainPage/MainMapSection.tsx
  src/components/mainPage/MainPage.tsx
  src/components/mainPage/MainRecommendSection.tsx
  src/components/mainPage/MainStampSection.tsx
  src/constants/icons.ts
  src/hooks/useModal.tsx
Labels: 기능 개발

#56 [#8]feat:사용자용 스탬프찍은 위치 별명 데이터에 같이 저장
  src/app/stamp-all/[id]/page.tsx
  src/components/stamp/MyLocation.tsx
  src/components/stamp/StampActive.tsx
  src/components/stamp/StampList.tsx
Labels: 기능 개발

#57 [#28]feat:이미지슬라이드n번째로 시작점변경
  src/app/photo-album/[region]/page.tsx
  src/components/photoalbum/AddPhotoBtn.tsx
  src/components/photoalbum/AlbumImgEdit.tsx
  src/components/photoalbum/AlbumList.tsx
  src/components/photoalbum/ImgModal.tsx
  src/components/stamp/MyLocation.tsx
  src/hooks/useImgModal.ts
Labels: 기능 개발

#58 관광상세페이지, 북마크 작업
  db.json
  package.json
  pnpm-lock.yaml
  src/app/tourism-detail/[id]/page.tsx
  src/app/tourism/page.tsx
  src/app/tourismDetail/[id]/page.tsx
  src/components/common/Icons/CreditcardIcon.tsx
  src/components/common/Icons/DayOffIcon.tsx
  src/components/common/Icons/ParkingIcon.tsx
  src/components/common/Icons/StrollerIcon.tsx
  src/components/common/Icons/TImeIcon.tsx
  src/components/tourism/bookMark.tsx
  src/components/tourism/placeCard.tsx
  src/queries/query.keys.ts
  src/serverActions/fetchPlacesAction.tsx
Labels: 기능 개발, 리팩토링

#61 [#60]feat:페이지연결,style:css
  src/app/layout.tsx
  src/components/common/nav/Nav.tsx
Labels: 기능 개발, 스타일

#63 [#60] 주소에따라 네비엑티브되게 추가+훅분리
  src/components/common/nav/Nav.tsx
  src/components/photoalbum/CategoryModal.tsx
  src/hooks/useNavActive.ts
Labels: 기능 개발

#64 [#59] 메인 페이지 컴포넌트 분리
  src/app/globals.css
  src/app/stamp-all/[id]/page.tsx
  src/app/stamp-map/page.tsx
  src/components/common/Icons/MainBackground.tsx
  src/components/common/Modal/StampModal.tsx
  src/components/common/nav/Nav.tsx
  src/components/mainPage/MainFooter.tsx
  src/components/mainPage/MainRecommendSection.tsx
  src/components/mainPage/MainStampSection.tsx
  src/components/stamp/StampList.tsx
  src/components/stampMap/KakaoMap.tsx
  src/components/stampMap/ScrollButtonSwiper.tsx
  src/constants/mapColor.ts
  src/constants/regions.ts
  src/hooks/useModal.tsx
  src/styles/swiper.css
Labels: 리팩토링

#66 [#65]스템프 찍은후 별명없을시 모달추가
  src/app/globals.css
  src/components/common/Modal/AliasCheckModal.tsx
  src/components/stamp/MyLocation.tsx
  src/components/stamp/StampList.tsx
Labels: 기능 개발

#67 [#44] 헤더 추가 Style/auth
  public/images/alert1.png
  public/images/alert2.png
  public/images/alert3.png
  public/images/apple-icon.png
  public/images/check1.png
  public/images/check2.png
  public/images/check3.png
  public/images/login-email-alert1.png
  public/images/login-pass-alert1.png
  public/images/logo.png
  public/images/pass-alert1.png
  public/images/pass-check1.png
  src/app/forgot-password/page.tsx
  src/app/globals.css
  src/app/landing/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/app/photo-album/page.tsx
  src/app/profile/page.tsx
  src/app/reset-password/page.tsx
  src/app/signup/[id]/page.tsx
  src/app/signup/page.tsx
  src/app/splash/page.tsx
  src/app/stamp-all/page.tsx
  src/app/stamp-map/page.tsx
  src/app/tourism/page.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/LogoutButton.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/login/EmailPasswordCheck.tsx
  src/components/auth/login/ForgotPasswordForm.tsx
  src/components/auth/login/ResetPasswordForm.tsx
  src/components/auth/signup/PasswordCheck.tsx
  src/components/auth/signup/PasswordCheckIconField.tsx
  src/components/auth/signup/StepEmailForm.tsx
  src/components/auth/signup/StepMainForm.tsx
  src/components/auth/signup/StepNicknameForm.tsx
  src/components/auth/signup/StepPasswordForm.tsx
  src/components/common/Buttons/Button.tsx
  src/components/common/InputField.tsx
  src/components/common/header/Header.tsx
  src/components/homepage.tsx
  src/components/landing/Landingpage.tsx
  src/components/mypage/MyPageLayout.tsx
  src/components/mypage/PhotoNum.tsx
  src/components/mypage/ProfileInfo.tsx
  src/components/mypage/ReNickname.tsx
  src/components/mypage/StampNum.tsx
  src/constants/icons.ts
  src/hooks/useAuthStatus.ts
  src/hooks/useHeaderActive.ts
  src/utils/supabase/auth.ts
  tailwind.config.ts
Labels: 버그, 리팩토링, 스타일

#69 [#44] 동적페이지도 헤더가 보이도록 수정
  src/hooks/useHeaderActive.ts
Labels: 버그

#71 [#60] 관련페이지 이동시에도 네비에 해당 버튼에 엑티브되도록Feat/nav
  src/components/common/nav/Nav.tsx
  src/hooks/useNavActive.ts
Labels: 기능 개발

#72 [#44] 헤더 상수화 및 튜터님 피드백 반영
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(root)/(stamp)/stamp-all/page.tsx
  src/app/(root)/(stamp)/stamp-map/page.tsx
  src/app/(root)/mypage/page.tsx
  src/app/layout.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/LogoutButton.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/login/ForgotPasswordForm.tsx
  src/components/auth/signup/PasswordCheck.tsx
  src/components/auth/signup/PasswordCheckIconField.tsx
  src/components/auth/signup/StepEmailForm.tsx
  src/components/auth/signup/StepMainForm.tsx
  src/components/auth/signup/StepNicknameForm.tsx
  src/components/auth/signup/StepPasswordForm.tsx
  src/components/common/Buttons/Button.tsx
  src/components/common/Buttons/LinkButton.tsx
  src/components/common/InputField.tsx
  src/components/common/header/Header.tsx
  src/components/landing/LandingIcons/ArrowIcon.tsx
  src/components/landing/LandingIcons/CameraIcon.tsx
  src/components/landing/LandingIcons/CompassIcon.tsx
  src/components/landing/Landingpage.tsx
  src/components/layout/Header.tsx
  src/components/mypage/MyPageLayout.tsx
  src/components/mypage/ReNickname.tsx
  src/constants/pageName.ts
  src/hooks/useHeaderActive.ts
Labels: 버그, 리팩토링

#73 [#60] 페이지상수화적용
  src/app/layout.tsx
  src/components/layout/Nav.tsx
  src/hooks/useNavActive.ts
Labels: 기능 개발

#74 북마크 목록페이지추가, 관광목록페이지, 관광디테일페이지 스타일 수정
  db.json
  pnpm-lock.yaml
  src/app/(root)/(tourism)/tourism-detail/[id]/page.tsx
  src/app/(root)/(tourism)/tourism/page.tsx
  src/app/(root)/book-mark/page.tsx
  src/components/common/Icons/CreditcardIcon.tsx
  src/components/common/Icons/DayOffIcon.tsx
  src/components/common/Icons/ParkingIcon.tsx
  src/components/common/Icons/StrollerIcon.tsx
  src/components/common/Icons/TImeIcon.tsx
  src/components/tourism/bookMark.tsx
  src/components/tourism/placeCard.tsx
  src/constants/icons.ts
  src/constants/pageName.ts
  src/hooks/useHeaderActive.ts
  src/serverActions/fetchPlacesAction.tsx
  src/serverActions/groupPlaces.tsx
Labels: 기능 개발, 스타일

#77 [#59] 메인페이지 리팩토링
  src/app/(root)/(tourism)/tourism-detail/[id]/page.tsx
  src/app/(root)/(tourism)/tourism/page.tsx
  src/app/page.tsx
  src/components/common/Modal/StampModal.tsx
  src/components/mainPage/MainFooter.tsx
  src/components/mainPage/MainRecommendSection.tsx
  src/components/mainPage/MainStampSection.tsx
  src/components/mainPage/TouristSwiper.tsx
  src/components/stampMap/KakaoMap.tsx
  src/components/stampMap/MapButtonSwiper.tsx
  src/components/tourism/placeCard.tsx
  src/queries/useMutations.ts
  src/serverActions/fetchPlacesAction.tsx
Labels: 리팩토링, 스타일

#79 [#76] 리팩토링,스탬프이미지업데이트
  public/images/busan-active.png
  public/images/busan.png
  public/images/daegu-active.png
  public/images/daegu.png
  public/images/daejeon-active.png
  public/images/daejeon.png
  public/images/gwangju-active.png
  public/images/gwangju.png
  public/images/incheon-active.png
  public/images/incheon.png
  public/images/preparing-img.png
  public/images/sejong-active.png
  public/images/sejong.png
  public/images/seoul-active.png
  public/images/seoul.png
  public/images/ulsan-active.png
  public/images/ulsan.png
  src/apis/fetchStampList.ts
  src/app/(root)/(stamp)/stamp-all/[id]/page.tsx
  src/app/(root)/(stamp)/stamp-tracking/page.tsx
  src/components/layout/Nav.tsx
  src/components/photoalbum/AlbumList.tsx
  src/components/stamp/MyLocation.tsx
  src/components/stamp/RegionNames.ts
  src/components/stamp/StampActive.tsx
  src/components/stamp/StampImg.ts
  src/components/stamp/StampItem.tsx
  src/components/stamp/StampList.tsx
  src/queries/query.keys.ts
  src/queries/useMutations.ts
  src/queries/useQuerys.ts
  src/serverActions/fetchStampActions.ts
Labels: 버그, 기능 개발, 리팩토링, 스타일

#82 [#59] 서버 액션 메서드명, readme 파일 수정
  README.md
  src/app/(root)/(stamp)/stamp-map/page.tsx
  src/components/common/Icons/MainBackgroundIcon.tsx
  src/components/mainPage/MainFooter.tsx
  src/components/mainPage/MainStampSection.tsx
  src/queries/useQuerys.ts
  src/serverActions/fetchStampActions.ts
Labels: 리팩토링, 문서

#81 [#75] auth 리팩토링 및 style작업
  src/app/(auth)/auth/callback/page.tsx
  src/app/api/auth/login/route.ts
  src/app/api/auth/logout/route.ts
  src/app/api/auth/signup/route.ts
  src/app/layout.tsx
  src/app/splash/page.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/LogoutButton.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/login/ForgotPasswordForm.tsx
  src/components/auth/login/ResetPasswordForm.tsx
  src/components/auth/signup/PasswordCheck.tsx
  src/components/auth/signup/PasswordCheckIconField.tsx
  src/components/auth/signup/StepEmailForm.tsx
  src/components/auth/signup/StepMainForm.tsx
  src/components/auth/signup/StepNicknameForm.tsx
  src/components/auth/signup/StepPasswordForm.tsx
  src/components/common/Buttons/Button.tsx
  src/components/common/Icons/LandingIcons/ArrowIcon.tsx
  src/components/common/Icons/LandingIcons/CameraIcon.tsx
  src/components/common/Icons/LandingIcons/CompassIcon.tsx
  src/components/common/Icons/SignupCompleteIcon.tsx
  src/components/common/InputField.tsx
  src/components/landing/Landingpage.tsx
  src/components/mypage/MyPageLayout.tsx
  src/components/mypage/ReNickname.tsx
  src/hooks/useAuthStatus.ts
  src/hooks/useSocialLogin.ts
  src/hooks/useUserNickname.ts
  src/middleware.ts
  src/utils/supabase/auth.ts
Labels: 리팩토링, 스타일

#85 [#44] 스플래쉬화면 바디패딩제거
  src/app/layout.tsx
Labels: 스타일

#86 [#51] 애니메이션추가
  src/app/globals.css
  src/components/stamp/StampActive.tsx
  tailwind.config.ts
Labels: 버그, 스타일

#88 리드미작성
  README.md
Labels: 문서

#90 [#59] 지도 폴리곤 선명도 올리기
  coordregioncode.json
Labels: 리팩토링

#87 북마크 리팩토링
  src/app/(root)/(tourism)/tourism-detail/[id]/page.tsx
  src/app/(root)/(tourism)/tourism/page.tsx
  src/app/(root)/book-mark/page.tsx
  src/components/mainPage/MainRecommendSection.tsx
  src/components/mainPage/TouristSwiper.tsx
  src/components/tourism/bookMark.tsx
  src/components/tourism/placeCard.tsx
  src/hooks/useUpdateBookmark.ts
  src/serverActions/fetchPlacesAction.tsx
Labels: 리팩토링

#91 [#75] 회원가입 버튼 위치수정
  src/components/auth/signup/StepEmailForm.tsx
  src/components/auth/signup/StepNicknameForm.tsx
  src/components/auth/signup/StepPasswordForm.tsx
Labels: 스타일

#92 [#59] 지도 버튼 스와이퍼 스타일 수정 & 메인 페이지 정보 없을 때 빈 값 처리
  src/components/common/Modal/StampModal.tsx
  src/components/mainPage/MainRecommendSection.tsx
  src/components/mainPage/MainStampSection.tsx
  src/components/stampMap/MapButtonSwiper.tsx
  src/styles/swiper.css
  tailwind.config.ts
Labels: 리팩토링, 스타일

#93 [#59] query 폴더 리팩토링
  src/app/(root)/(stamp)/stamp-all/[id]/page.tsx
  src/app/(root)/(stamp)/stamp-map/page.tsx
  src/app/(root)/(tourism)/tourism-detail/[id]/page.tsx
  src/app/(root)/(tourism)/tourism/page.tsx
  src/components/common/Modal/StampModal.tsx
  src/components/mainPage/MainRecommendSection.tsx
  src/components/mainPage/MainStampSection.tsx
  src/components/mainPage/TouristSwiper.tsx
  src/components/stamp/MyLocation.tsx
  src/components/stamp/StampList.tsx
  src/components/stampMap/KakaoMap.tsx
  src/constants/mapColor.ts
  src/hooks/useStamp.ts
  src/middleware.ts
  src/queries/mutation/useAliasMutation.ts
  src/queries/query.keys.ts
  src/queries/query/useStampQuery.ts
  src/queries/useMutations.ts
  src/queries/useQuerys.ts
  src/serverActions/groupPlaces.tsx
  src/serverActions/placeActions.tsx
  src/serverActions/stampActions.ts
Labels: 리팩토링

#94 [#76] 클라
  src/app/(root)/(stamp)/stamp-all/[id]/page.tsx
  src/components/common/Modal/StampModal.tsx
  src/components/stamp/MyLocation.tsx
  src/components/stamp/StampActive.tsx
  src/components/stamp/StampItem.tsx
  src/components/stamp/StampList.tsx
  src/components/stamp/getStampLocation.ts
  src/queries/query/useStampQuery.ts
  src/serverActions/stampActions.ts
  src/utils/promptLogin.ts
  src/utils/region/RegionNames.ts
Labels: 버그, 기능 개발, 리팩토링

#96 [#95] 폴더 리팩토링
  src/apis/place.ts
  src/apis/stamp.ts
  src/apis/user.ts
  src/app/(auth)/auth/callback/page.tsx
  src/app/(root)/(stamp)/stamp-all/[id]/page.tsx
  src/app/(root)/(stamp)/stamp-map/page.tsx
  src/app/(root)/(tourism)/tourism/page.tsx
  src/app/(root)/book-mark/page.tsx
  src/app/(root)/photo-album/[region]/page.tsx
  src/components/mainPage/MainRecommendSection.tsx
  src/components/mainPage/MainStampSection.tsx
  src/components/mainPage/TouristSwiper.tsx
  src/components/mypage/PhotoNum.tsx
  src/components/mypage/ReNickname.tsx
  src/components/mypage/StampNum.tsx
  src/components/photoalbum/AlbumList.tsx
  src/components/stamp/MyLocation.tsx
  src/components/stamp/StampActive.tsx
  src/components/stamp/StampList.tsx
  src/components/stampMap/KakaoMapMarker.tsx
  src/components/stampMap/ReSetttingMapBounds.tsx
  src/components/tourism/placeCard.tsx
  src/hooks/useGeoData.ts
  src/hooks/useKakaoMap.ts
  src/hooks/useStamp.ts
  src/hooks/useUserId.ts
  src/queries/mutation/useAliasMutation.ts
  src/queries/query/useStampQuery.ts
  src/store/mapStore.ts
  src/types/place/place.type.ts
  src/types/stamp.ts
  src/types/stamp/addressProps.type.ts
  src/types/stamp/coordRegionCode.type.ts
  src/types/stamp/stamp.type.ts
  src/utils/fetchUser.ts
  src/utils/place/placeGroupFormatter.ts
  src/utils/region/pathListFormatter.ts
  src/utils/region/siDoFormatter.ts
Labels: 리팩토링

#100 [#97] 수퍼베이스 stamp 타입 설정
  pnpm-lock.yaml
  src/apis/stamp.ts
  src/app/(root)/(stamp)/stamp-all/[id]/page.tsx
  src/app/(root)/(tourism)/tourism/page.tsx
  src/components/mainPage/MainRecommendSection.tsx
  src/components/mainPage/MainStampSection.tsx
  src/components/mainPage/TourlistSwiper.tsx
  src/components/stamp/StampItem.tsx
  src/components/stampMap/KakaoMapMarker.tsx
  src/queries/mutation/usePostStampMutaion.ts
  src/queries/query/useStampQuery.ts
  src/serverActions/stamp.ts
  src/store/mapStore.ts
  src/types/stamp/stamp.type.ts
  src/types/supabase/database.type.ts
  src/types/supabase/table.type.ts
  src/utils/region/siDoFormatter.ts
  src/utils/supabase/client.ts
  src/utils/supabase/server.ts
Labels: 기능 개발

#102 [#76] 앨범 삭제뮤테이션 분리
  src/apis/stamp.ts
  src/components/stamp/StampActive.tsx
  src/queries/mutation/useDeleteStampMutation.ts
Labels: 리팩토링

#103 [#99] 카테고리모달 디폴트 서울로변경, 편집시 선택방식변경
  src/apis/fetchAlbumList.ts
  src/apis/photoAlbum.ts
  src/app/(root)/(stamp)/stamp-all/[id]/page.tsx
  src/app/(root)/photo-album/[region]/page.tsx
  src/components/photoalbum/AddPhotoBtn.tsx
  src/components/photoalbum/AlbumList.tsx
  src/components/photoalbum/CategoryModal.tsx
  src/components/photoalbum/EditAlbumImg.tsx
  src/components/photoalbum/ImgModal.tsx
  src/components/photoalbum/TopTitle.tsx
  src/components/stamp/GetUserAddress.tsx
  src/components/stamp/StampActive.tsx
  src/hooks/useAlbumDelete.ts
  src/hooks/useAlbumList.ts
  src/queries/mutation/useAlbumMutation.ts
  src/queries/query.keys.ts
  src/queries/query/useAlbumQuery.ts
  src/types/stamp/Address.types.ts
  src/utils/region/RegionNames.ts
Labels: 버그, 기능 개발, 리팩토링

#107 [#76] 뮤테이션합침,컴포넌트명수정,불필요한훅정리
  src/app/(root)/(stamp)/stamp-all/[id]/page.tsx
  src/app/(root)/photo-album/[region]/page.tsx
  src/components/photoalbum/AddPhotoBtn.tsx
  src/components/photoalbum/AlbumList.tsx
  src/components/photoalbum/AlbumTitleTab.tsx
  src/components/photoalbum/ModalAlbumImg.tsx
  src/components/photoalbum/RegionCategoryModal.tsx
  src/components/stamp/MyLocation.tsx
  src/components/stamp/StampActive.tsx
  src/hooks/useDropdoun.ts
  src/queries/mutation/useDeleteStampMutation.ts
  src/queries/mutation/usePostAliasMutation.ts
  src/queries/mutation/usePostStampMutaion.ts
  src/queries/mutation/useStampMutaion.ts
Labels: 버그, 리팩토링

#109 [#105]푸터 기본레이아웃
  public/images/logo_dark.png
  src/app/globals.css
  src/app/layout.tsx
  src/components/layout/Footer.tsx
Labels: 스타일

#110 [#106] tourism 리팩토링
  src/apis/bookmark.ts
  src/apis/tourism.ts
  src/app/(root)/(stamp)/stamp-map/page.tsx
  src/app/(root)/(tourism)/tourism-detail/[id]/page.tsx
  src/app/(root)/(tourism)/tourism/page.tsx
  src/app/(root)/book-mark/page.tsx
  src/app/(root)/tourism/[id]/page.tsx
  src/app/(root)/tourism/loading.tsx
  src/app/(root)/tourism/page.tsx
  src/app/splash/page.tsx
  src/components/common/Loading/Loading.tsx
  src/components/mainPage/MainRecommendSection.tsx
  src/components/mainPage/MainStampSection.tsx
  src/components/mainPage/TourlistSwiper.tsx
  src/components/tourism/PlaceCard.tsx
  src/components/tourism/TourismDetail.tsx
  src/hooks/useUpdateBookmark.ts
  src/queries/mutation/useAlbumMutation.ts
  src/queries/mutation/useBookmarkMutation.ts
  src/queries/query.keys.ts
  src/queries/query/useAlbumQuery.ts
  src/queries/query/useBookmarkQuery.ts
  src/queries/query/useStampQuery.ts
  src/queries/query/useTourismQuery.ts
  src/serverActions/place.ts
  src/serverActions/tourism.ts
  src/types/supabase/database.type.ts
  src/types/supabase/table.type.ts
  src/types/tourism/tourism.type.ts
  src/utils/place/placeGroupFormatter.ts
  src/utils/tourism/tourismGroupFormatter.ts
Labels: 리팩토링

#101 [#75] 로그인 회원가입 코드 분리
  src/apis/photoCount.ts
  src/apis/stampCount.ts
  src/app/(auth)/auth/callback/page.tsx
  src/app/(auth)/auth/callback/route.ts
  src/app/(auth)/forgot-password/page.tsx
  src/app/(auth)/reset-password/page.tsx
  src/app/api/auth/authService.ts
  src/components/auth/LoginForm.tsx
  src/components/auth/LogoutButton.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/login/EmailPasswordCheck.tsx
  src/components/auth/login/ForgotPasswordForm.tsx
  src/components/auth/login/ResetPasswordForm.tsx
  src/components/auth/signup/PasswordCheck.tsx
  src/components/auth/signup/PasswordCheckIconField.tsx
  src/components/auth/signup/StepEmailForm.tsx
  src/components/auth/signup/StepNicknameForm.tsx
  src/components/auth/signup/StepPasswordForm.tsx
  src/components/common/Buttons/Button.tsx
  src/components/common/Buttons/SocialLoginButton.tsx
  src/components/common/InputField.tsx
  src/components/common/InputField/InputField.tsx
  src/components/common/InputField/InputFieldStyles.ts
  src/components/mainPage/MainStampSection.tsx
  src/components/mypage/MyPageLayout.tsx
  src/components/mypage/NicknameEditor.tsx
  src/components/mypage/PhotoCount.tsx
  src/components/mypage/PhotoNum.tsx
  src/components/mypage/StampCount.tsx
  src/components/mypage/StampNum.tsx
  src/hooks/useConfirmPassword.tsx
  src/hooks/useSignupFormState.ts
  src/hooks/useSocialLogin.ts
  src/queries/query.keys.ts
  src/types/supabase/database.type.ts
  src/utils/supabase/auth.ts
Labels: 리팩토링, 스타일

#112 [#99] 앨범 반응형
  public/images/photo-arrow-next.png
  public/images/photo-arrow-prev.png
  src/app/(root)/(stamp)/stamp-all/[id]/page.tsx
  src/app/(root)/(stamp)/stamp-all/page.tsx
  src/app/(root)/photo-album/[region]/page.tsx
  src/app/globals.css
  src/components/layout/Footer.tsx
  src/components/photoalbum/AddPhotoBtn.tsx
  src/components/photoalbum/AlbumList.tsx
  src/components/photoalbum/AlbumTitleTab.tsx
  src/components/photoalbum/EditAlbumImg.tsx
  src/components/photoalbum/ModalAlbumImg.tsx
  src/components/photoalbum/RegionCategoryModal.tsx
  src/components/photoalbum/RoundedArrowButton.tsx
  src/hooks/useAlbumDelete.ts
  src/hooks/useImgModal.ts
  src/styles/album.css
  src/styles/stamp.css
Labels: 버그, 기능 개발, 스타일

#114 [#116] 관광지추천 반응형
  src/app/(root)/tourism/page.tsx
  src/app/globals.css
  src/components/mainPage/TourlistSwiper.tsx
  src/components/tourism/PlaceCard.tsx
  src/components/tourism/TourismDetail.tsx
  src/styles/tourism.css
Labels: 스타일

#115 [#111] 메인 페이지 반응형을 위한 swiper 분리
  public/images/mainMap.png
  src/app/(root)/book-mark/page.tsx
  src/app/(root)/tourism/page.tsx
  src/app/page.tsx
  src/components/common/Icons/Icon.tsx
  src/components/common/Modal/StampModal.tsx
  src/components/mainPage/MainMapSection.tsx
  src/components/mainPage/MainRecommendSection.tsx
  src/components/mainPage/MainStampSection.tsx
  src/components/mainPage/swiper/MainTourismCard.tsx
  src/components/mainPage/swiper/MainTourismSwiper.tsx
  src/components/tourism/TourismCard.tsx
  src/components/tourism/TourismSwiper.tsx
Labels: 스타일

#116 [#75] 헤더 추가
  public/images/apple-icon2.png
  public/images/row_logo_dark.png
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/reset-success/page.tsx
  src/app/(auth)/update-password/page.tsx
  src/app/(auth)/update-success/page.tsx
  src/app/(root)/mypage/page.tsx
  src/app/layout.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/reset/ResetPasswordForm.tsx
  src/components/auth/reset/ResetSuccess.tsx
  src/components/auth/signup/StepEmailForm.tsx
  src/components/auth/signup/StepNicknameForm.tsx
  src/components/auth/signup/StepPasswordForm.tsx
  src/components/auth/update/UpdatePasswordForm.tsx
  src/components/auth/update/UpdateSuccess.tsx
  src/components/common/Buttons/SocialLoginButton.tsx
  src/components/common/Icons/MoaLogo.tsx
  src/components/common/InputField/InputField.tsx
  src/components/layout/Header.tsx
  src/components/mypage/UserMenu.tsx
  src/constants/icons.ts
  src/constants/pageName.ts
  src/hooks/useConfirmPassword.tsx
  src/hooks/useHeaderActive.ts
  src/hooks/useSocialLogin.ts
Labels: 기능 개발, 스타일

#117 [#75] 헤더 아래 마진 추가
  src/app/(auth)/login/page.tsx
  src/app/(auth)/reset-password/page.tsx
  src/app/(auth)/reset-success/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(auth)/update-password/page.tsx
  src/app/(auth)/update-success/page.tsx
  src/app/(root)/(stamp)/stamp-all/page.tsx
  src/app/(root)/mypage/page.tsx
  src/app/(root)/tourism/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/layout/Header.tsx
  src/components/mypage/UserMenu.tsx
  src/components/photoalbum/AlbumList.tsx
Labels: 버그, 스타일

#119 Update README.md
  README.md
Labels: 문서

#120 [#111] 메인 페이지 반응형 작업
  public/images/mainMap.png
  public/images/marker/busan.png
  public/images/marker/chungcheongbuk.png
  public/images/marker/chungcheongnam.png
  public/images/marker/daegu.png
  public/images/marker/daejeon.png
  public/images/marker/gangwon.png
  public/images/marker/gwangju.png
  public/images/marker/gyeonggi.png
  public/images/marker/gyeongsangbuk.png
  public/images/marker/gyeongsangnam.png
  public/images/marker/incheon.png
  public/images/marker/jeju.png
  public/images/marker/jeollabuk.png
  public/images/marker/jeollanam.png
  public/images/marker/sejong.png
  public/images/marker/seoul.png
  public/images/marker/ulsan.png
  src/app/(root)/tourism/page.tsx
  src/components/common/Icons/MoaLogo.tsx
  src/components/layout/Header.tsx
  src/components/mainPage/MainFooter.tsx
  src/components/mainPage/MainRecommendSection.tsx
  src/components/mainPage/MainStampSection.tsx
  src/components/mainPage/swiper/MainTourismCard.tsx
  src/components/mainPage/swiper/MainTourismSwiper.tsx
  src/components/stampMap/KakaoMapMarker.tsx
  src/components/stampMap/MapButtonSwiper.tsx
  src/components/tourism/TourismCard.tsx
  src/components/tourism/TourismDetail.tsx
  src/constants/regions.ts
  src/hooks/useMediaSize.ts
  src/styles/mainTourismSwiper.css
Labels: 스타일

#122 Update README.md
  README.md
Labels: 문서

#123 [#121] 지도 반응형
  src/components/common/Modal/StampModal.tsx
  src/components/mainPage/MainRecommendSection.tsx
  src/components/mainPage/swiper/MainTourismCard.tsx
  src/components/mainPage/swiper/MainTourismSwiper.tsx
  src/components/stampMap/KakaoMap.tsx
  src/components/stampMap/MapButtonSwiper.tsx
  src/styles/mainSwiper.css
  src/styles/mapSwiper.css
  src/styles/tourism.css
Labels: 스타일

#126 [#118] a태그 Link태그로 변경!
  public/images/alert1.png
  public/images/alert2.png
  public/images/alert3.png
  public/images/apple-icon.png
  public/images/check1.png
  public/images/check2.png
  public/images/check3.png
  public/images/pass-alert1.png
  public/images/pass-check1.png
  src/app/(root)/photo-album/[region]/page.tsx
  src/app/api/auth/authService.ts
  src/app/layout.tsx
  src/app/splash/page.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/LogoutButton.tsx
  src/components/auth/signup/StepEmailForm.tsx
  src/components/auth/signup/StepMainForm.tsx
  src/components/auth/signup/StepPasswordForm.tsx
  src/components/auth/update/UpdatePasswordForm.tsx
  src/components/common/Icons/SignupCompleteIcon.tsx
  src/components/common/Icons/SmailCheckIcon.tsx
  src/components/common/Icons/SmailXIcon.tsx
  src/components/common/InputField/InputField.tsx
  src/components/common/InputField/InputFieldStyles.ts
  src/components/landing/Landingpage.tsx
  src/components/layout/Header.tsx
  src/components/mypage/PhotoCount.tsx
  src/components/mypage/StampCount.tsx
  src/components/mypage/UserMenu.tsx
  src/components/tourism/TourismDetail.tsx
Labels: 버그, 리팩토링

#127 [#125] pc랜딩페이지 반응형
  public/images/footer/team01.png
  public/images/footer/team02.png
  public/images/footer/team03.png
  public/images/footer/team04.png
  public/images/footer/team05.png
  public/images/landing/section1-1.png
  public/images/landing/section1-2.png
  public/images/landing/section2-bg.png
  public/images/landing/section2-phoneL.png
  public/images/landing/section2-phoneR.png
  public/images/landing/section3-icon1.png
  public/images/landing/section3-icon2.png
  public/images/landing/section3-icon3.png
  public/images/landing/section3-icon4.png
  public/images/landing/section3-icon5.png
  public/images/landing/section3-phone.png
  public/images/landing/section4-phone.png
  public/images/landing/section4-slide1.png
  public/images/landing/section4-slide2.png
  public/images/landing/section4-slide3.png
  public/images/landing/section4-slide4.png
  public/images/landing/section4-slide5.png
  src/app/(root)/(stamp)/stamp-all/[id]/page.tsx
  src/app/globals.css
  src/components/landing/Landingpage.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Nav.tsx
  src/styles/landing.css
Labels: 스타일

#131 [#130] 마이페이지 자잘한 오류 수정
  public/images/login-email-alert1.png
  public/images/login-pass-alert1.png
  public/images/mypage_img.png
  public/images/mypage_img2.png
  src/components/auth/LoginForm.tsx
  src/components/auth/LogoutButton.tsx
  src/components/common/InputField/InputField.tsx
  src/components/mypage/MyPageLayout.tsx
  src/components/mypage/PhotoCount.tsx
  src/components/mypage/RecentPhoto.tsx
  src/components/mypage/UserMenu.tsx
  src/hooks/useSignupFormState.ts
  src/hooks/useSocialLogin.ts
Labels: 기능 개발, 리팩토링, 스타일

#132 [#118] refact: 주석제거
  src/components/auth/LogoutButton.tsx
  src/components/mypage/MyPageLayout.tsx
Labels: 리팩토링

#133 [#124] 스와이퍼 오류
  src/app/(root)/book-mark/page.tsx
  src/app/(root)/tourism/loading.tsx
  src/app/(root)/tourism/page.tsx
  src/components/auth/LoginForm.tsx
  src/components/common/Loading/LoadingSpin.tsx
  src/components/mainPage/MainRecommendSection.tsx
  src/components/mainPage/MainStampSection.tsx
  src/components/stampMap/KakaoMap.tsx
  src/components/stampMap/MapButtonSwiper.tsx
  src/styles/mainSwiper.css
  src/styles/mapSwiper.css
  src/styles/tourism.css
  tailwind.config.ts
Labels: 버그, 긴급

#135 [#128][#125] 메인슬라이드 사라짐문제해결,그 외 오류수정
  src/app/(root)/(stamp)/stamp-all/[id]/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/common/Loading/LoadingSpin.tsx
  src/components/landing/Landingpage.tsx
  src/components/layout/Nav.tsx
  src/components/mainPage/swiper/MainTourismSwiper.tsx
  src/components/photoalbum/AlbumList.tsx
  src/components/stamp/GetUserAddress.tsx
  src/components/stamp/StampList.tsx
  src/components/stampMap/KakaoMap.tsx
  src/components/stampMap/MapButtonSwiper.tsx
  src/styles/mainSwiper.css
  src/styles/mapSwiper.css
Labels: 버그, 긴급

#136 [#134] 북마크 페이지 반응형 작업
  src/app/(root)/(stamp)/stamp-all/[id]/page.tsx
  src/app/(root)/book-mark/page.tsx
Labels: 스타일

#137 [#124] 에러, not-found 추가
  src/app/(root)/(stamp)/stamp-all/[id]/page.tsx
  src/app/(root)/tourism/[id]/page.tsx
  src/app/error.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/components/common/Icons/Loading/CameraIcon.tsx
  src/components/common/Loading/Loading.tsx
  src/components/mainPage/MainRecommendSection.tsx
  src/components/mainPage/MainStampSection.tsx
  src/components/mainPage/swiper/MainTourismSwiper.tsx
  src/components/stamp/StampList.tsx
  src/components/stampMap/KakaoMap.tsx
  src/hooks/useStamp.ts
  src/serverActions/stamp.ts
  src/serverActions/tourism.ts
  src/styles/mainSwiper.css
Labels: 기능 개발

#139 [#138] 카카오맵 최대 13레벨까지만 맵 축소 제한
  src/components/stampMap/KakaoMap.tsx
  src/components/stampMap/KakaoMapMaxLevel.tsx
  src/components/stampMap/MapButtonSwiper.tsx
Labels: 버그

#141 [#140] 메인 <-> 랜딩 페이지 위치변경
  src/app/(root)/home/page.tsx
  src/app/page.tsx
Labels: 리팩토링

#146 [#145] css추가수정
  src/app/(root)/(stamp)/stamp-all/[id]/page.tsx
  src/app/layout.tsx
  src/components/common/Modal/StampModal.tsx
  src/components/landing/Landingpage.tsx
  src/components/layout/Header.tsx
  src/components/layout/Nav.tsx
  src/components/mainPage/swiper/MainTourismSwiper.tsx
  src/components/stamp/GetUserAddress.tsx
  src/constants/regions.ts
  src/queries/mutation/useBookmarkMutation.ts
  src/queries/query/useTourismQuery.ts
  src/styles/landing.css
  src/styles/mainSwiper.css
  src/styles/mapSwiper.css
  src/utils/region/RegionNames.ts
Labels: 버그, 스타일

#148 [#147] 헤더 서버사이드로 분리
  src/components/auth/LoginForm.tsx
  src/components/landing/Landingpage.tsx
  src/components/layout/ClientHeaderMenu.tsx
  src/components/layout/Header.tsx
  src/components/mypage/MyPageLayout.tsx
  src/components/stamp/GetUserAddress.tsx
  src/constants/pageName.ts
  src/hooks/useHeaderActive.ts
Labels: 긴급

#153 [#144] UT 전 오류 수정
  src/app/(root)/book-mark/page.tsx
  src/components/common/Icons/MainBackgroundIcon.tsx
  src/components/mainPage/MainFooter.tsx
  src/components/mainPage/MainRecommendSection.tsx
  src/components/mainPage/MainStampSection.tsx
  src/components/mainPage/swiper/MainTourismSwiper.tsx
  src/components/mypage/MyPageLayout.tsx
  src/components/mypage/NicknameEditor.tsx
  src/components/mypage/PhotoCount.tsx
  src/components/stamp/GetUserAddress.tsx
  src/components/stamp/StampList.tsx
  src/queries/mutation/useBookmarkMutation.ts
  src/queries/query.keys.ts
  src/queries/query/useTourismQuery.ts
  src/styles/mainSwiper.css
Labels: 버그, 긴급

#155 [#154] 환경변수 수정
  src/components/auth/LoginForm.tsx
  src/components/auth/reset/ResetPasswordForm.tsx
  src/hooks/useSocialLogin.ts
Labels: 버그, 긴급

#158 [#154] 소셜로그인 재수정
  src/components/auth/reset/ResetPasswordForm.tsx
  src/hooks/useSocialLogin.ts
Labels: 긴급

#159 Release 1.0.2
  src/components/auth/reset/ResetPasswordForm.tsx
  src/hooks/useSocialLogin.ts
Labels: 버그, 배포

#166 [#163] 스탬프 히스토리 클릭 시 지도 마커로 이동
  src/app/(root)/(stamp)/layout.tsx
  src/app/(root)/(stamp)/stamp-all/[id]/page.tsx
  src/app/(root)/(stamp)/stamp-map/page.tsx
  src/components/stamp/GetUserAddress.tsx
  src/components/stampMap/KakaoMap.tsx
  src/components/stampMap/ReSetttingMapBounds.tsx
  src/hooks/map/useKakaoMap.ts
  src/store/mapStore.ts
Labels: 기능 개발

#165 [#145][#164][#165] 앨범로그인안했을때 리다이렉트추가, 로그인유저의 북마크값 가져오기,온보딩기본레이아웃
  public/images/landing/section3-phone-1.png
  src/app/(root)/(stamp)/stamp-tracking/page.tsx
  src/app/(root)/photo-album/[region]/page.tsx
  src/app/(root)/photo-album/page.tsx
  src/app/(root)/tourism/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/landing/LandingStart.tsx
  src/components/landing/LandingTutorial.tsx
  src/components/landing/Landingpage.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Nav.tsx
  src/components/mainPage/MainRecommendSection.tsx
  src/components/photoalbum/AlbumAddBtn.tsx
  src/components/photoalbum/AlbumEditImg.tsx
  src/components/photoalbum/AlbumImgArrowBtn.tsx
  src/components/photoalbum/AlbumImgModal.tsx
  src/components/photoalbum/AlbumList.tsx
  src/components/photoalbum/AlbumRegionCategoryModal.tsx
  src/components/photoalbum/AlbumTitleTab.tsx
  src/components/stamp/StampGetUserAddress.tsx
  src/components/stamp/StampLocationErrorMsg.ts
  src/components/stamp/StampMyLocation.tsx
  src/styles/landing.css
  tailwind.config.ts
Labels: 버그, 리팩토링, 스타일

#169 [#167] 지도 가로 스크롤 클릭 시 스와이퍼 이동
  src/components/mainPage/MainRecommendSection.tsx
  src/components/stampMap/KakaoMap.tsx
  src/components/stampMap/swiper/KakaoMapSwiper.tsx
  src/hooks/map/useKakaoMap.ts
Labels: 기능 개발

#172 [#170] 헤더및 마이페이지 디테일 부 분 수정
  public/images/auth/apple-icon2.png
  public/images/auth/google-icon.png
  public/images/auth/kakao-icon.png
  public/images/favicon.png
  public/images/moa_thumbnail.png
  public/images/mypage/mypage_img.png
  public/images/mypage/mypage_img2.png
  src/app/layout.tsx
  src/app/page.tsx
  src/components/auth/DesktopSignupForm.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/reset/ResetPasswordForm.tsx
  src/components/auth/signup/StepMainForm.tsx
  src/components/auth/signup/StepPasswordForm.tsx
  src/components/common/Icons/Auth/SignupCompleteIcon.tsx
  src/components/common/Icons/Auth/SmailCheckIcon.tsx
  src/components/common/Icons/Auth/SmailXIcon.tsx
  src/components/common/InputField/InputField.tsx
  src/components/layout/Header.tsx
  src/components/mypage/MyPageLayout.tsx
  src/components/mypage/PhotoCount.tsx
  src/components/mypage/UserMenu.tsx
  src/hooks/auth/useSocialLogin.ts
  src/providers/HistoryProvider.tsx
Labels: 스타일

#173 [#170] 소셜로그인 이미지경로 수정 및 전북 이미지 파일명 수정
  public/images/stamp/jeollabuk-active.png
  src/components/common/Buttons/SocialLoginButton.tsx
  src/components/stamp/StampItem.tsx
Labels: 버그

#174 [#168] 온보딩 높이값 수정
  src/components/landing/LandingTutorial.tsx
  src/styles/landing.css
Labels: 스타일

#177 Update README.md
  README.md
Labels: 문서

#179 [#178]{#168] 데이터반영늦는오류 수정
  src/app/(root)/(stamp)/stamp-all/page.tsx
  src/app/(root)/photo-album/[region]/page.tsx
  src/app/(root)/photo-album/page.tsx
  src/components/common/Modal/AlbumImgModal.tsx
  src/components/common/Modal/AlbumRegionCategoryModal.tsx
  src/components/common/Modal/StampAliasCheckModal.tsx
  src/components/common/Modal/StampModal.tsx
  src/components/landing/LandingStart.tsx
  src/components/landing/LandingTutorial.tsx
  src/components/layout/Nav.tsx
  src/components/mypage/RecentPhoto.tsx
  src/components/photoalbum/AlbumAddBtn.tsx
  src/components/photoalbum/AlbumList.tsx
  src/components/stamp/StampActive.tsx
  src/components/stamp/StampList.tsx
  src/components/stamp/StampMyLocation.tsx
  src/hooks/album/useImgModal.ts
  src/hooks/queries/query/useAlbumQuery.ts
  src/hooks/queries/query/useStampQuery.ts
  src/services/apis/photoAlbum.ts
  src/services/serverActions/photoAlbum.ts
  src/services/serverActions/stamp.ts
  src/styles/landing.css
Labels: 버그, 스타일

#180 [#162] 회원가입시 유효성검사 추가 및 마이페이지 리팩토링
  public/images/favicon.png
  src/app/(auth)/auth/callback/route.ts
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/page.tsx
  src/components/auth/DesktopSignupForm.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/LogoutButton.tsx
  src/components/auth/MobileSignupForm.tsx
  src/components/auth/signup/StepEmailForm.tsx
  src/components/auth/update/UpdatePasswordForm.tsx
  src/components/common/Buttons/SocialLoginButton.tsx
  src/components/common/Modal/LogoutModal.tsx
  src/components/common/Modal/NicknameEditorModal.tsx
  src/components/layout/Header.tsx
  src/components/mypage/MyPageLayout.tsx
  src/components/mypage/MyPageNicknameEditor.tsx
  src/components/mypage/MyPagePhotoCount.tsx
  src/components/mypage/MyPageRecentPhoto.tsx
  src/components/mypage/MyPageStampCount.tsx
  src/components/mypage/NicknameEditor.tsx
  src/components/mypage/UserMenu.tsx
  src/hooks/auth/useSocialLogin.ts
  src/hooks/useUserMenuState.ts
  src/services/apis/mypage.ts
  src/services/apis/stampCount.ts
Labels: 버그, 리팩토링, 스타일

#182 [#181] 앨범 이미지 압축 성능최적화
  package.json
  pnpm-lock.yaml
  public/images/footer/team01-min.png
  public/images/footer/team02-min.png
  public/images/footer/team03-min.png
  public/images/footer/team04-min.png
  public/images/footer/team05-min.png
  src/app/(root)/photo-album/[region]/page.tsx
  src/app/(root)/photo-album/loading.tsx
  src/components/common/Modal/AlbumRegionCategoryModal.tsx
  src/components/layout/Footer.tsx
  src/components/photoalbum/AlbumAddBtn.tsx
  src/components/photoalbum/AlbumList.tsx
Labels: 버그, 리팩토링

#183 [#176] 지도 스탬프 보러가기 눌렀을 때 undefined 오류 수정
  src/components/common/Modal/LogoutModal.tsx
  src/components/common/Modal/NicknameEditorModal.tsx
  src/components/common/Modal/StampAliasCheckModal.tsx
  src/components/common/Modal/StampModal.tsx
  src/components/mypage/MyPageLayout.tsx
  src/components/photoalbum/AlbumAddBtn.tsx
  src/components/stampMap/KakaoMap.tsx
Labels: 버그

#184 Update README.md
  README.md
Labels: 문서

#186 [#185] 리드미 파일 수정
  README.md
Labels: 문서

#188 [#185] 리드미 수정
  README.md
Labels: 문서

#189 [#162] auth 코드 분리
  public/images/auth/apple-icon2.png
  src/app/(auth)/signup/[id]/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/LogoutButton.tsx
  src/components/auth/reset/ResetPasswordForm.tsx
  src/components/auth/signup/SignupForm.tsx
  src/components/auth/signup/desktop/DesktopSignupForm.tsx
  src/components/auth/signup/mobile/MobileSignupForm.tsx
  src/components/auth/signup/mobile/StepEmailForm.tsx
  src/components/auth/signup/mobile/StepMainForm.tsx
  src/components/auth/signup/mobile/StepNicknameForm.tsx
  src/components/auth/signup/mobile/StepPasswordForm.tsx
  src/components/auth/update/UpdatePasswordForm.tsx
  src/components/common/Buttons/SocialLoginButton.tsx
  src/components/common/InputField/InputField.tsx
  src/components/common/Loading/Loading.tsx
  src/components/common/Modal/LogoutModal.tsx
  src/components/common/Modal/NicknameEditorModal.tsx
  src/components/common/Modal/StampModal.tsx
  src/components/common/auth/PasswordMatchStatus.tsx
  src/components/layout/ClientHeaderMenu.tsx
  src/components/layout/Header.tsx
  src/components/mypage/MyPageNicknameEditor.tsx
  src/components/mypage/MyPagePhotoCount.tsx
  src/components/mypage/MyPageRecentPhoto.tsx
  src/components/mypage/MyPageStampCount.tsx
  src/components/mypage/UserMenu.tsx
  src/hooks/auth/useAuthListener.ts
  src/hooks/auth/useSignupFormState.ts
  src/hooks/auth/useSocialLogin.ts
  src/hooks/map/useStamp.ts
  src/hooks/mypage/useUserMenuState.ts
  src/services/serverActions/photoAlbum.ts
  src/utils/auth/loginValidation.ts
  src/utils/auth/passwordValidation.ts
Labels: 리팩토링

#192 [#145] 모바일랜딩 튜툐리얼 마지막 여행떠나기버튼 수정
  src/components/landing/LandingTutorial.tsx
  src/styles/landing.css
Labels: 스타일

#191 [#185] 리드미 수정
  README.md
Labels: 문서

#194 [#190] 추억모음 pc버전 추가
  src/app/(root)/home/page.tsx
  src/components/mypage/MyPageLayout.tsx
  src/components/mypage/MyPageRecentPhoto.tsx
Labels: 기능 개발, 긴급

#196 [#118] type분리 및 비밀번호 재설정 오류 해결
  src/components/auth/LoginForm.tsx
  src/components/auth/reset/ResetPasswordForm.tsx
  src/components/auth/signup/desktop/DesktopSignupForm.tsx
  src/components/auth/signup/mobile/StepEmailForm.tsx
  src/components/auth/signup/mobile/StepMainForm.tsx
  src/components/auth/signup/mobile/StepNicknameForm.tsx
  src/components/auth/signup/mobile/StepPasswordForm.tsx
  src/components/auth/update/UpdatePasswordForm.tsx
  src/components/mypage/MyPageNicknameEditor.tsx
  src/components/mypage/MyPageRecentPhoto.tsx
  src/components/mypage/UserMenu.tsx
  src/types/auth/auth.type.ts
  src/types/mypage/mypage.type.ts
Labels: 버그, 리팩토링

#195 #[193] PWA 적용
  package.json
  pnpm-lock.yaml
  public/app-icon-192x192.png
  public/app-icon-512x512.png
  public/app-icon.png
  src/app/layout.tsx
  src/app/manifest.ts
Labels: 기능 개발

#198 [#197] 앱 아이콘 사이즈 수정
  public/app-icon-512x512.png
Labels: 버그

#199 [#197] 앱 아이콘 사이즈 오류 수정
  public/app-icon-192x192.png
  public/app-icon-512x512.png
  public/app-icon.png
Labels: 버그

#200 추억 모음 inner-w 추가
  src/components/mypage/MyPageRecentPhoto.tsx
Labels: 스타일

#201 [#197] 앱 아이콘 여백 수정
  public/app-icon-192x192.png
Labels: 버그

#203 [#145] 디자이너 수정요청건
  public/images/landing/section1-1-1.png
  public/images/landing/section3-icon5.png
  public/images/landing/section3-phone-2.png
  src/app/globals.css
  src/components/landing/LandingTutorial.tsx
  src/components/landing/Landingpage.tsx
  src/components/layout/Footer.tsx
  src/styles/landing.css
  tailwind.config.ts
Labels: 스타일

#204 Update README.md
  README.md
Labels: 문서

#206 [#185] 리드미 파일 트러블 슈팅 추가
  README.md
Labels: 문서

#207 [#145] 로그인되어있을때 랜딩페이지 라우터처리
  src/components/landing/LandingTutorial.tsx
Labels: 스타일

#208 Release 1.2.1
  README.md
  public/images/landing/section1-1-1.png
  public/images/landing/section3-icon5.png
  public/images/landing/section3-phone-2.png
  src/app/globals.css
  src/components/landing/LandingTutorial.tsx
  src/components/landing/Landingpage.tsx
  src/components/layout/Footer.tsx
  src/components/mainPage/MainStampSection.tsx
  src/styles/landing.css
  tailwind.config.ts
Labels: 버그, 문서, 스타일, 배포

#209 [#185] 리드미 수정
  README.md
Labels: 문서
