Repository smu06030/st8, pull requests merged in 2024-10, with the labels that each got.

#10 Feat/stamp
  .env
  public/images/대구광역시.png
  public/images/부산광역시.png
  public/images/서울시.png
  public/images/인천.png
  public/images/전라북도.png
  src/app/stamp-all/[id]/page.tsx
  src/app/stamp-all/page.tsx
  src/app/stamp-tracking/page.tsx
  src/components/stamp/MyLocation.tsx
  src/components/stamp/StampActive.tsx
  src/components/stamp/StampImg.ts
  src/components/stamp/StampItem.tsx
  src/components/stamp/StampList.tsx
  src/components/stamp/StampRecentList.tsx
  src/middleware.ts
  src/server/fetchStampList.ts
  src/types/stamp.ts
  src/types/stamp/AddressPropsType.ts
  src/utils/supabase/client.ts
  tailwind.config.ts
Labels: 기능 개발

#11 fix:빌드 전 안쓰는 변수 제거
  .env
  .eslintrc.json
  src/components/stamp/MyLocation.tsx
  src/utils/supabase/middleware.ts
Labels: 버그

#12 fix:esLint 수정
  .eslintrc.json
  src/utils/supabase/middleware.ts
Labels: 버그

#13 [#6] 회원가입과 로그인 기능 Feat/signup
  .gitignore
  pull_request_template.md
  src/app/api/auth/login/route.ts
  src/app/api/auth/logout/route.ts
  src/app/api/auth/signup/route.ts
  src/app/logIn/page.tsx
  src/app/mypage/page.tsx
  src/app/signup/page.tsx
  src/components/LoginForm.tsx
  src/components/SignupForm.tsx
  src/components/myPage/MyPageLayout.tsx
  src/components/myPage/ProfileManager.tsx
  src/store/authStore.ts
  src/utils/supabase/middleware.ts
  tailwind.config.ts
Labels: 기능 개발, 리팩토링

#17 [#6] 로그인 회원가입 zustand 삭제 및 hook-form 추가 Feat/login
  package.json
  pnpm-lock.yaml
  pull_request_template.md
  src/components/LoginForm.tsx
  src/components/myPage/ProfileManager.tsx
  src/hooks/useKakaoLoader.ts
  src/store/authStore.ts
Labels: 리팩토링

#18 [#14] 카카오맵 가로 스크롤 버튼 임시 제작
  src/app/kakaomap/page.tsx
  src/components/kakaomap/ScrollButtonSwiper.tsx
  src/utils/region/pathListFormatter.ts
Labels: 기능 개발

#20 Feat/stamp
  .eslintrc.json
  public/images/대구.png
  public/images/부산.png
  public/images/서울.png
  public/images/전북특별자치도.png
  src/apis/fetchStampList.ts
  src/app/stamp-all/[id]/page.tsx
  src/app/stamp-all/page.tsx
  src/app/stamp-tracking/page.tsx
  src/components/stamp/LocationErrorMsg.ts
  src/components/stamp/MyLocation.tsx
  src/components/stamp/StampActive.tsx
  src/components/stamp/StampImg.ts
  src/components/stamp/StampItem.tsx
  src/components/stamp/StampList.tsx
  src/components/stamp/StampRecentList.tsx
  src/server/fetchStampList.ts
  src/types/stamp.ts
  src/types/stamp/AddressProps.types.ts
  src/utils/fetchUser.ts
  tailwind.config.ts
  tsconfig.json
Labels: 기능 개발, 리팩토링

#21 [#19] 카카오맵 행정구역 가로스크롤 기능 구현
  src/app/kakaomap/page.tsx
  src/components/kakaomap/ScrollButtonSwiper.tsx
  src/hooks/useGeoData.ts
  src/styles/swiper.css
  src/utils/region/siDoFormatter.ts
Labels: 버그, 기능 개발

#23 Feat/stamp
  src/app/globals.css
  src/components/stamp/StampItem.tsx
  tailwind.config.ts
Labels: 스타일

#29 Feat/photo album
  public/images/default-image.png
  src/apis/fetchStampList.ts
  src/app/photo-album/page.tsx
  src/app/stamp-all/[id]/page.tsx
  src/components/photoalbum/AlbumList.tsx
  src/components/stamp/MyLocation.tsx
Labels: 기능 개발

#27 [#7][#26] 관광지 목록페이지 제작 & 빌드오류 수정
  next.config.mjs
  src/app/tourism/page.tsx
  src/app/tourismDetail/[id]/page.tsx
  tsconfig.json
Labels: 버그, 기능 개발

#32 [#30] 마이페이지 빌드오류 해결 Fix/mypage
  src/app/api/auth/auth-login/route.ts
  src/app/api/auth/logout/route.ts
  src/app/api/auth/signup/route.ts
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/app/profile/page.tsx
  src/app/signup/page.tsx
  src/components/LoginForm.tsx
  src/components/myPage/MyPageLayout.tsx
  src/components/mypage/MyPageLayout.tsx
  src/components/mypage/ProfileInfo.tsx
  src/components/mypage/ProfileManager.tsx
  src/components/mypage/StampNum.tsx
Labels: 버그

#33 [#22] 행정구역 별 스탬프 마커 찍기
  src/apis/fetchStampList.ts
  src/app/layout.tsx
  src/app/stamp-map/loading.tsx
  src/app/stamp-map/page.tsx
  src/components/stampMap/KakaoMap.tsx
  src/components/stampMap/KakaoMapLoader.tsx
  src/components/stampMap/KakaoMapMarker.tsx
  src/components/stampMap/ReSetttingMapBounds.tsx
  src/components/stampMap/ScrollButtonSwiper.tsx
  src/hooks/useGeoData.ts
  src/hooks/useStamp.ts
  src/hooks/useUser.ts
  src/queries/query.keys.ts
  src/queries/useQuerys.ts
  src/serverActions/fetchStampActions.ts
  src/types/stampMap/CoordRegionCode.types.ts
  src/types/stampMap/Stamp.types.ts
  src/utils/region/pathListFormatter.ts
  src/utils/region/siDoFormatter.ts
Labels: 기능 개발, 리팩토링

#37 [#36] 카카오맵, 스크롤 버튼 리팩토링
  src/app/stamp-map/page.tsx
  src/components/common/Icons/.gitkeep
  src/components/stampMap/KakaoMap.tsx
  src/components/stampMap/KakaoMapOverlay.tsx
  src/components/stampMap/ScrollButtonSwiper.tsx
  src/hooks/useKakaoMap.ts
  src/providers/mapStoreProvider.tsx
  src/store/mapStore.ts
Labels: 리팩토링

#38 [#34] 카카오맵 커스텀 오버레이 기능 개발
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/images/marker-pin-01.svg
  src/app/layout.tsx
  src/components/stampMap/KakaoMap.tsx
  src/components/stampMap/KakaoMapMarker.tsx
  src/components/stampMap/KakaoMapOverlay.tsx
  src/hooks/useKakaoMap.ts
  src/store/mapStore.ts
  src/types/stampMap/Stamp.types.ts
  tailwind.config.ts
Labels: 기능 개발

#41 [#28] 지역별 이미지 추가기능
  src/apis/fetchAlbumList.ts
  src/apis/fetchStampList.ts
  src/app/globals.css
  src/components/photoalbum/AddPhotoBtn.tsx
  src/components/photoalbum/AlbumList.tsx
  src/components/photoalbum/CategoryModal.tsx
Labels: 버그, 기능 개발

#43 [#28]앨범삭제기능, 이미지확대팝업 추가
  src/apis/fetchAlbumList.ts
  src/components/photoalbum/AddPhotoBtn.tsx
  src/components/photoalbum/AlbumList.tsx
  src/components/photoalbum/CategoryModal.tsx
  src/components/photoalbum/ImgModal.tsx
Labels: 버그, 기능 개발
